-- Single source of truth for the schema: executed at startup against the in-memory H2
-- and parsed at build time by jOOQ's DDLDatabase to generate the type-safe DSL.

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_number  VARCHAR(32)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_customers_tax_number UNIQUE (tax_number)
);

CREATE TABLE accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(32)  NOT NULL,
    customer_id  BIGINT        NOT NULL,
    balance      NUMERIC(19,2) NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_accounts_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    -- Last line of defence: even a bug in the service layer can never persist a negative balance.
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE INDEX ix_accounts_customer ON accounts (customer_id);

-- Append-only ledger. 'amount' is signed (credits positive, debits negative).
CREATE TABLE ledger_entries (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                   BIGINT        NOT NULL,
    kind                         VARCHAR(16)   NOT NULL,
    amount                       NUMERIC(19,2) NOT NULL,
    balance_after                NUMERIC(19,2) NOT NULL,
    counterparty_account_number  VARCHAR(32),
    transfer_id                  VARCHAR(36),
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_ledger_amount_non_zero CHECK (amount <> 0),
    CONSTRAINT ck_ledger_kind CHECK (kind IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_OUT', 'TRANSFER_IN'))
);

CREATE INDEX ix_ledger_account ON ledger_entries (account_id, id);
